server:
  port: 8081

spring:
  datasource:
   # type: org.apache.tomcat.jdbc.pool.Datasource
    url: jdbc:postgresql://localhost:5432/bitcoin
    username: root
    password: root
    initialization-mode: always
   
    
mybatis:
  mapper-locations: classpath*:*.xml

#logging:
#  level:
#    root: debug
  
  #  '[com.anymind]': trace
